image_path: /home/ac/data/2023/zhanzechao/image_editing/dataset/fashiongen/valid/00019.png
save_path: out
prompt: "t-shirt in green."
prior_prompt: ""
mode: ""
seed: 105
inversion_steps: 0.8
seg_prompt: ""
mask_prompt: ""
image_dir: ""
outdir: "/home/ac/data/2023/zhanzechao/ours/MADiff/output"
mconfig: "mask_est/inference.yaml"
dconfig: "madiff/sar/v1-inference.yaml"
ckpt: "checkpoints/v1-5-pruned-emaonly.ckpt"
ddim_steps: 50
skip_inversion: false
attn_record_end: 35
attn_record_start: 45
skip_save: false
scale: 7.5
ddim_eta: 0.0
n_iter: 1
H: 512
W: 512
C: 4
f: 8
n_samples: 1
precision: "autocast"